---
- name: Lesson01 Task3
  hosts: node3
  become: true
  tasks:

  - name: Add parameters to Grub
    lineinfile:
      state: present
      path: /etc/default/grub
      backrefs: true
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* Listefnames=0 biosdevname=0)\"[^\"]+)(\".*)'
      line: '\1 Listefnames=0 biosdevname=0\2'
    notify: grub_cfg

  handlers:
    - name: grub_cfg
      ansible.builtin.service:
        name: httpd
        state: restarted
