---
- name: Lesson01 Task2
  hosts: all
  become: true
  tasks:

  - name: Stop and disable httpd service
    service:
      name: httpd
      state: stopped
      enabled: no

  - name: close port 80 for service
    firewalld:
      service: http
      permanent: true
      state: disabled

  - name: close port 443 for service
    firewalld:
      service: https
      permanent: true
      state: disabled


  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted

  - name: Remove Apache web-server
    package:
      name: httpd
      state: absent

  - name: Remove file with text
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent